FROM consol/sakuli-ubuntu-xfce:v1.0.2

MAINTAINER Tobias Schneck "tobias.schneck@consol.de"
ENV REFRESHED_AT 2016-11-02
ENV TZ=Europe/Berlin

## Install a PDF viewer
RUN apt-get update && apt-get install -y libqt4-svg \
    && wget -qO- http://get.code-industry.net/public/master-pdf-editor-4.0.30_qt4.amd64.tar.gz | tar xzs -C /root \
    && ln -s /root/master-pdf-editor-4/masterpdfeditor4 /usr/bin/masterpdfeditor4

## ADD is only need due to docker-in-docker jenkins can`t currently mount volumens
ADD . /opt/tests
