FROM consol/sakuli-centos-xfce:v1.0.1

MAINTAINER Tobias Schneck "tobias.schneck@consol.de"
ENV REFRESHED_AT 2016-06-16
ENV TZ=Europe/Berlin

## Install a PDF viewer
RUN yum install -y http://get.code-industry.net/public/master-pdf-editor3-3.7.10-1.x86_64.rpm

## ADD is only need due to docker-in-docker jenkins can`t currently mount volumens
ADD . /opt/tests
