FROM consol/sakuli-centos-xfce:v1.0.0

MAINTAINER Tobias Schneck "tobias.schneck@consol.de"
ENV REFRESHED_AT 2016-03-04

ENV VNC_RESOLUTION 1024x768
## ADD is only need due to docker-in-docker jenkins can`t currently mount volumens
ADD . /opt/tests
