FROM consol/sakuli-centos-xfce:v1.0.2

MAINTAINER Tobias Schneck "tobias.schneck@consol.de"
ENV REFRESHED_AT 2016-11-02
ENV TZ=Europe/Berlin

## Install a PDF viewer
RUN yum install -y http://get.code-industry.net/public/master-pdf-editor-4.0.30_qt5.x86_64.rpm && yum clean all

## ADD is only need due to docker-in-docker jenkins can`t currently mount volumens
ADD . /opt/tests
